---
title: Blog
timezone: UTC
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
    test: test
  uploads:
    title: Uploads
    output: true
name: Scott Logic
description: This feed is brought to you by Scott Logic's team of technical authors
  and bloggers, covering topics including HTML5, iOS, C#, process, UX and practically
  anything else relating to software development.
canonical:
  url: https://blog.scottlogic.com
scottlogic:
  url: https://www.scottlogic.com
permalink: "/:year/:month/:day/:title.html"
safe: true
twitter_handle: Scott_Logic
plugins:
- jekyll-redirect-from
kramdown:
  input: kramdown
paginate: 20
excerpt_separator: ''
emptyArray: []
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- lintPosts.js
- scss
- node_modules
- package.json
- README.md
- ".spelling"
- scripts/jquery-1.9.1.js
- scripts/jquery.jscroll-2.2.4.js
- scripts/tweet.js
- scripts/search.js
- scripts/feed.js
- vendor
