version: 2
jobs:
    spellcheck:
        docker:
            - image: circleci/node:10.9-browsers
        steps:
            - checkout
            - restore_cache:
                key: v0-blog-yarn-cache-{{ checksum "yarn.lock" }}
            - run:
                command: |
                    yarn install
            - save_cache:
                key: v0-blog-yarn-cache-{{ checksum "yarn.lock" }}
                paths:
                    - ./node_modules
            - run: yarn test
workflows:
    version: 2
    build_and_test:
        jobs:
            - spellcheck